"""
Django settings for empsureProj project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATE_DIR = os.path.join(BASE_DIR, "templates")
STATIC_DIR = os.path.join(BASE_DIR,"static")
MEDIA_DIR = os.path.join(BASE_DIR,"media")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '5djvvbt5ql9^p(tzmidush-(q3h%p*4)8+yvg^e-rp0d6a_n(0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [ '127.0.0.1',
                  'localhost',
                  ]

# Application definition

INSTALLED_APPS = [
    'empsureApp',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'empsureProj.urls'

TEMPLATE_DIR = os.path.join(BASE_DIR, 'templates')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ TEMPLATE_DIR ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'django.template.context_processors.static'
            ],
        },
    },
]

WSGI_APPLICATION = 'empsureProj.wsgi.application'

# import pymysql
# pymysql.install_as_MySQLdb()

import pymysql
pymysql.version_info = (1, 4, 0, "final", 0)
pymysql.install_as_MySQLdb()

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'empsure',
        'USER': 'empsure',
        'PASSWORD': 'empsure',
        'HOST': 'localhost',
        'PORT': 3306,
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]

# superuser created
# admin, passowrd = admin

LOGIN_REDIRECT_URL = "../../empsureApp/main"
LOGOUT_REDIRECT_URL = "../../empsureApp/main"

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [ STATIC_DIR,]

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = "/media/"

# Nov 18 15:53:23 ip-172-31-24-208 web: STATIC_DIR : /var/app/current/static
# Nov 18 15:53:23 ip-172-31-24-208 web: MEDIA_DIR : /var/app/current/media
# Nov 18 15:53:23 ip-172-31-24-208 web: AWS_STORAGE_BUCKET_NAME : empsure-static-media
# Nov 18 15:53:23 ip-172-31-24-208 web: AWS_S3_CUSTOM_DOMAIN : empsure-static-media.s3.amazonaws.com
# Nov 18 15:53:23 ip-172-31-24-208 web: AWS_S3_OBJECT_PARAMETERS : {'CacheControl': 'max-age=86400'}
# Nov 18 15:53:23 ip-172-31-24-208 web: AWS_DEFAULT_ACL : public-read
# Nov 18 15:53:23 ip-172-31-24-208 web: AWS_LOCATION : static
# Nov 18 15:53:23 ip-172-31-24-208 web: STATIC_URL : https://empsure-static-media.s3.amazonaws.com/static/
# Nov 18 15:53:23 ip-172-31-24-208 web: STATICFILES_STORAGE : storages.backends.s3boto3.S3Boto3Storage
# Nov 18 15:53:23 ip-172-31-24-208 web: STATIC_ROOT : /var/app/current/static
# Nov 18 15:53:23 ip-172-31-24-208 web: DEFAULT_FILE_STORAGE : empsureProj.storage_backends.MediaStorage
# Nov 18 15:53:23 ip-172-31-24-208 web: MEDIA_ROOT : /var/app/current/media
# Nov 18 15:53:23 ip-172-31-24-208 web: MEDIA_URL : https://empsure-static-media.s3.amazonaws.com/media/
