# Generated by Django 3.1.3 on 2020-11-18 03:14

from django.db import migrations, models
import django.db.models.deletion
import empsureApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('idbonus', models.AutoField(db_column='idBonus', primary_key=True, serialize=False)),
                ('bonusvalue', models.DecimalField(db_column='bonusValue', decimal_places=2, max_digits=10)),
                ('bonusdate', models.DateField(db_column='bonusDate')),
            ],
            options={
                'db_table': 'tbbonus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('iddocument', models.AutoField(db_column='idDocument', primary_key=True, serialize=False)),
                ('document', models.FileField(blank=True, db_column='nameDocument', upload_to=empsureApp.models.document_file_name)),
                ('date_time', models.DateTimeField()),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'db_table': 'tbdocument',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documenttype',
            fields=[
                ('iddocumenttype', models.AutoField(db_column='idDocumentType', primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'tbdocumenttype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('idemployee', models.AutoField(db_column='idEmployee', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='firstName', max_length=45)),
                ('lastname', models.CharField(db_column='lastName', max_length=45)),
                ('birthdate', models.DateField(db_column='birthDate')),
                ('contractinitialdate', models.DateField(db_column='contractInitialDate')),
                ('contractfinaldate', models.DateField(blank=True, db_column='contractFinalDate', null=True)),
                ('username', models.CharField(db_column='username', max_length=20)),
            ],
            options={
                'db_table': 'tbemployee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('idfunction', models.AutoField(db_column='idFunction', primary_key=True, serialize=False)),
                ('initialdate', models.DateField(db_column='initialDate')),
                ('finaldate', models.DateField(blank=True, db_column='finalDate', null=True)),
            ],
            options={
                'db_table': 'tbfunction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FunctionType',
            fields=[
                ('idfunctiontype', models.AutoField(db_column='idFunctionType', primary_key=True, serialize=False)),
                ('functiontype', models.CharField(db_column='functionType', max_length=45)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'db_table': 'tbfunctiontype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('idimage', models.AutoField(db_column='idImage', primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, db_column='nameImage', upload_to=empsureApp.models.image_file_name)),
                ('typeimage', models.CharField(db_column='typeImage', max_length=1)),
                ('date_time', models.DateTimeField(db_column='date_time')),
                ('resultauthentication', models.FloatField(blank=True, db_column='resultAuthentication', null=True)),
            ],
            options={
                'db_table': 'tbimage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('idpayment', models.AutoField(db_column='idPayment', primary_key=True, serialize=False)),
                ('grosspayment', models.DecimalField(db_column='grossPayment', decimal_places=2, max_digits=10)),
                ('discounts', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paymentdate', models.DateField(db_column='paymentDate')),
            ],
            options={
                'db_table': 'tbpayment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('idposition', models.AutoField(db_column='idPosition', primary_key=True, serialize=False)),
                ('initialdate', models.DateField(db_column='initialDate')),
                ('finaldate', models.DateField(blank=True, db_column='finalDate', null=True)),
                ('statusrh', models.IntegerField(blank=True, db_column='statusRH', null=True)),
            ],
            options={
                'db_table': 'tbposition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PositionType',
            fields=[
                ('idpositiontype', models.AutoField(db_column='idPositionType', primary_key=True, serialize=False)),
                ('positiontype', models.CharField(db_column='positionType', max_length=45)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'db_table': 'tbpositiontype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SiteOperation',
            fields=[
                ('idsiteoperation', models.AutoField(db_column='idSiteOperation', primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=45)),
                ('country', models.CharField(max_length=45)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'db_table': 'tbsiteoperation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VacationDate',
            fields=[
                ('idvacationdate', models.AutoField(db_column='idVacationDate', primary_key=True, serialize=False)),
                ('datevacation', models.DateField(db_column='dateVacation')),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'tbvacationdate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VacationGrant',
            fields=[
                ('idvacationgrant', models.AutoField(db_column='idVacationGrant', primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('qtydays', models.IntegerField(db_column='qtyDays')),
            ],
            options={
                'db_table': 'tbvacationgrant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wage',
            fields=[
                ('idwage', models.AutoField(db_column='idWage', primary_key=True, serialize=False)),
                ('wagevalue', models.DecimalField(db_column='wageValue', decimal_places=2, max_digits=10)),
                ('initialdate', models.DateField(db_column='initialDate')),
                ('finaldate', models.DateField(blank=True, db_column='finalDate', null=True)),
            ],
            options={
                'db_table': 'tbwage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employeesiteoperation',
            fields=[
                ('employee', models.OneToOneField(db_column='idEmployee', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='empsureApp.employee')),
                ('initialdate', models.DateField(db_column='initialDate')),
                ('finaldate', models.DateField(blank=True, db_column='finalDate', null=True)),
            ],
            options={
                'db_table': 'tbemployeesiteoperation',
                'managed': False,
            },
        ),
    ]
